name: rentwheel_mobile
description: RentWheel mobile app — Flutter frontend untuk backend Laravel RentWheel.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  pdf: ^3.11.1
  printing: ^5.13.3
  image_picker: ^1.0.7
  file_picker: ^10.3.2

  http: ^1.2.1
  shared_preferences: ^2.2.3
  intl: ^0.19.0
  cupertino_icons: ^1.0.8
  image_picker_for_web: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

# Catatan:
# File ini hanya starter. Jalankan `flutter create .` di folder mobile/
# terlebih dahulu supaya struktur project Flutter lengkap (android/, ios/, dll)
# ter-generate, baru jalankan `flutter pub get`.
